[workspace]
channels = ["conda-forge"]
description = "Paper-to-Video Agentic System"
name = "mpresenter"
platforms = ["linux-64"]
version = "0.1.0"

[dependencies]
python = "3.10.*"
pip = "*"
ffmpeg = "*"
regex = "*"

[pypi-dependencies]
openai = ">=1.0.0"
pillow = ">=10.0.0"
pyttsx3 = ">=2.90"
paddleocr = ">=3.3.2, <4"
paddlepaddle = ">=3.2.2, <4"
opencv-python-headless = ">=4.8.0.74, <4.12"
pymupdf = ">=1.26.7, <2"
torch = "==2.6.0"
torchaudio = "==2.6.0"
numpy = "<2"
setproctitle = "==1.3.3"
attrdict = "==2.0.1"
librosa = "==0.10.2.post1"
langdetect = "==1.0.9"
pydub = "==0.25.1"
pyloudnorm = "==0.1.1"
modelscope = ">=1.28.0, <2"
addict = ">=2.4.0"
simplejson = ">=3.3.0"
HyperPyYAML = ">=1.2.2"
omegaconf = ">=2.3.0"
soundfile = ">=0.12.1"
onnxruntime-gpu = ">=1.18.0"
inflect = ">=7.3.1"
conformer = "==0.3.2"
diffusers = "==0.29.0"
hydra-core = "==1.3.2"
lightning = "==2.2.4"
gdown = "==5.1.0"
wget = "==3.2"
pyworld = "==0.3.4"
sortedcontainers = ">=1.5.9"
WeTextProcessing = "==1.0.4.1"
transformers = ">=4.41.2,<=4.49.0,!=4.46.*,!=4.47.*,!=4.48.*"
x-transformers = "==1.44.4"
torchdiffeq = "==0.2.5"
openai-whisper = "==20240930"
httpx = "==0.28.1"
gradio = "==5.23.1"
matplotlib = ">=3.10.8, <4"
datasets = ">=3.0.0, <=3.6.0"
